## Numpy Tutorial

Numpy è un modulo Python che viene utilizzato per eseguire vari calcoli numerici in Python. I calcoli effettuati utilizzando gli array Numpy sono più veloci dei normali array Python. 

Inoltre, il modulo Pandas è costruito su array numpy, quindi una migliore comprensione di Numpy può aiutarci a 
utilizzare Pandas in modo più efficace.

In [1]:
import numpy as np

### Definizione di array

Definizone di array unidimensionale.

In [2]:
arr1 = np.array(['abc',34,12.09])   # array() è una funzione della libreria numpy che serve a creare un array
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
['abc' '34' '12.09']


Definizone di array multidimensionale.

In [3]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(arr2))
print(arr2)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Accesso ai dati

In [4]:
# Shape: dimensioni

print(arr1.shape)
print(arr2.shape)

(3,)
(3, 3)


In [5]:
# Data type: mi dice il tipo di dato contenuto nell'array

print(arr1.dtype)
print(arr2.dtype)

<U5
int32


In [6]:
# Accesso ai dati

print(arr1[1])

print(arr2[1][2])

34
6


### Array di zeri

In [7]:
# Creiamo una matrice di zeri 3x3

arr_zeros = np.zeros((3,3), dtype=int)
arr_zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Array di uni

In [8]:
# Creiamo una matrice di uni 2x4

arr_ones = np.ones((2,4), dtype=int)
arr_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### Matrice diagonale

In [9]:
# Creiamo una matrice diagonale

matr_diagonale = np.eye(5, dtype=int)
print(matr_diagonale)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### Operazioni tra matrici e scalari

In [10]:
# Addizione

matr_diagonale + 3

array([[4, 3, 3, 3, 3],
       [3, 4, 3, 3, 3],
       [3, 3, 4, 3, 3],
       [3, 3, 3, 4, 3],
       [3, 3, 3, 3, 4]])

In [11]:
# Moltiplicazione

matr_diagonale*2

array([[2, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 2]])

### Cambiare il tipo del dato

Per svolgere questa operazione viene utilizzato il metodo *astype*.

In [12]:
matr_diagonale.astype(np.str)            # conversione in Stringa

array([['1', '0', '0', '0', '0'],
       ['0', '1', '0', '0', '0'],
       ['0', '0', '1', '0', '0'],
       ['0', '0', '0', '1', '0'],
       ['0', '0', '0', '0', '1']], dtype='<U11')

In [13]:
matr_diagonale.astype(np.float32)        # conversione in decimale

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

## Boolean Indexing

In [14]:
# Generazione di array unidimensionale casuale

array_cas = np.random.randn(5)                     # random è un sottomodulo di numpy. In random c'è la funz randn() che genera
                                                   # array di numeri estratti randomicamente da una distribuzione noramale
print(array_cas)                                   # standardizzata

[-1.18190926  0.72753608  1.76199586  0.41126991 -0.33105995]


In [15]:
# Genero un array bidimensionale di numeri random

matrix_cas = np.random.randn(5,5)
print(matrix_cas)

# Genero un array di indice per tale matrice

indici = np.array(['a','b','c','a','e'])
print(indici)

print(indici=='a')   # condizione

# Ora esprimo la condizione come filtro sulle righe dell'array (dato che si tratta di indice)

matrix_cas[indici=='a']   # restituisce solo le righe in corrispondenza delle quali il filtro sull'indice risulta True

[[ 0.82667843 -0.67433289 -0.64383189  1.43158618 -0.39874236]
 [-0.12369503 -0.56665184 -0.00688937  0.02894749  1.32332573]
 [-1.14358972  0.36688434 -0.14934124  1.28597753  0.66549769]
 [ 0.63829815 -0.56364556 -0.01890466 -0.56308697  1.61459564]
 [ 0.66602755 -0.07004134 -0.71840912 -0.68852232  2.24960276]]
['a' 'b' 'c' 'a' 'e']
[ True False False  True False]


array([[ 0.82667843, -0.67433289, -0.64383189,  1.43158618, -0.39874236],
       [ 0.63829815, -0.56364556, -0.01890466, -0.56308697,  1.61459564]])

In [16]:
# Analogamente

print(matrix_cas[indici!='a'])
print()

# oppure

print(matrix_cas[(indici=='b')|(indici=='c')])
print()

# oppure

print(matrix_cas[(matrix_cas<1)])    # restituisce tutti gli elementi inferiri a 1
print()

[[-0.12369503 -0.56665184 -0.00688937  0.02894749  1.32332573]
 [-1.14358972  0.36688434 -0.14934124  1.28597753  0.66549769]
 [ 0.66602755 -0.07004134 -0.71840912 -0.68852232  2.24960276]]

[[-0.12369503 -0.56665184 -0.00688937  0.02894749  1.32332573]
 [-1.14358972  0.36688434 -0.14934124  1.28597753  0.66549769]]

[ 0.82667843 -0.67433289 -0.64383189 -0.39874236 -0.12369503 -0.56665184
 -0.00688937  0.02894749 -1.14358972  0.36688434 -0.14934124  0.66549769
  0.63829815 -0.56364556 -0.01890466 -0.56308697  0.66602755 -0.07004134
 -0.71840912 -0.68852232]



### Modifica delle dimensioni di un array

In [17]:
# Genero un array unidimensionale di numeri

lista = np.arange(0,16)
print(lista)
print(type(lista))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>


In [18]:
# Modifico la sua shape tramite il metodo reshape() della classe ndarray

lista_modified = lista.reshape(4,4)
lista_modified

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
# Selezione di elementi della matrice

lista_modified[2][1]

9

In [20]:
# Genero la sua trasposta

lista_trasposta = lista_modified.T
lista_trasposta

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])